# Generated by Django 3.0.4 on 2020-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pi_monitor", "0003_auto_20201008_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisdiction",
            name="desc",
            field=models.CharField(default="", max_length=255),
        ),
    ]
