#!/bin/sh

set -e


cd "$(dirname "$0")/.."

. ./.env
script/build

echo "==> Creating detached docker process..."
docker run --env-file .env --rm -d --name $DOCKER_IMAGE_NAME -v ${PWD}/bake_dir:/bake_dir mysocietyorg/$DOCKER_IMAGE_NAME:latest python manage.py bake $@

echo "==> Creating connecting to log process (can safely exit)..."
script/logs --follow