#!/bin/sh
#
# script/build: builds the project
#

set -e

cd "$(dirname "$0")/.."
export $(grep -v '^#' .env | xargs)

if [ "$1" = "--all" ]; then
    script/bake
    exit $?
fi

script/update

# Build the image
docker build -t mysocietyorg/$DOCKER_IMAGE_NAME:latest .

# Tag it with a timestamp
NOW=$(date +%s)
docker tag mysocietyorg/$DOCKER_IMAGE_NAME:latest mysocietyorg/$DOCKER_IMAGE_NAME:${NOW}

# Extract the database
CONTAINER=$(docker create mysocietyorg/$DOCKER_IMAGE_NAME:latest)
docker cp ${CONTAINER}:/app/databases/db.sqlite3 databases/db.sqlite3
docker container rm $CONTAINER
