#!/bin/sh
#
# script/build: builds the project
#

set -e

cd "$(dirname "$0")/.."
. script/config.sh

if [ "$1" = "--all" ]; then
    script/bake
    exit $?
fi

script/update

# Build the image
docker build -t mysocietyorg/$docker_image_name:latest .

# Tag it with a timestamp
NOW=$(date +%s)
docker tag mysocietyorg/$docker_image_name:latest mysocietyorg/$docker_image_name:${NOW}

# Extract the database
CONTAINER=$(docker create mysocietyorg/foi_monitor:latest)
docker cp ${CONTAINER}:/app/databases/db.sqlite3 databases/db.sqlite3
docker container rm $CONTAINER
