#!/bin/sh
#
# script/console: opens bash on docker instance
#

set -e

cd "$(dirname "$0")/.."

. script/config.sh

docker run --env-file .env -it -v ${PWD}/bake_dir:/bake_dir mysocietyorg/$docker_image_name:latest bash